# File: .github/workflows/docker_build.yml
name: Docker Build Workflow

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t my-image:${{ github.sha }} .
